#! /bin/sh

if [ $# -ne 2 ]; then
	echo "usage: $(basename $0) svn-url repo-name"
	exit 1
fi

SVN_URL=$1
NAME=$2

. ~/priv/gh-mir-ror.sh

DIR=$(dirname $0)/svn
GIT_URL="https://$GITHUB_USER:$GITHUB_PASS@github.com/$GITHUB_USER/$NAME"

if [ -e "$DIR/$NAME" ]; then
	echo "Already syncing $NAME"
	echo "TODO: check url"
	exit 1
fi


(
	mkdir -p "$DIR/$NAME" &&
	cd "$DIR/$NAME" &&
	git init --bare &&
	GIT_DIR="$PWD" git svn --prefix=svn/ -s init "$SVN_URL" &&
	git remote add origin  "$GIT_URL" &&
	git config --add remote.origin.push 'refs/remotes/svn/trunk:refs/heads/master' &&
	git config --add remote.origin.push 'refs/remotes/svn/*:refs/heads/*' &&
	ghr create "$NAME" "from $SVN_URL" &&
	git svn fetch &&
	git push origin
) || { exit 1; }

touch "$DIR/$NAME.sync"
